// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\motor_dtf_antiwindup\motor_dtf_antiwindup.v
// Created: 2023-04-27 20:25:27
// 
// Generated by MATLAB 9.11 and HDL Coder 3.19
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.001
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: motor_dtf_antiwindup
// Source Path: motor_dtf_antiwindup
// Hierarchy Level: 0
// 
// Simulink model description for motor_dtf_antiwindup:
// 
// Symmetric FIR Filter
// This example shows how to use HDL Coder(TM) to check, generate,
// and verify HDL for a fixed-point symmetric FIR filter. 
// 
// Simulink subsystem description for motor_dtf_antiwindup:
// 
// Symmetric FIR Filter
// This example shows how to use HDL Coder(TM) to check, generate,
// and verify HDL for a fixed-point symmetric FIR filter. 
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module motor_dtf_antiwindup;




  // All logic inside the DUT 'motor_dtf_antiwindup' was detected to be redundant by HDL Coder. Consider connecting 
  // output ports to the design in order to preserve logic for code generation


endmodule  // motor_dtf_antiwindup

